thin-provisioning/device_tree.h
thin-provisioning/thin_scan.cc

Code cleanup for new dev-tools

---

man8/thin_ls.8

forgot to update the man page with the new fields

update this_ls man page with new fields

---

persistent-data/space-maps/disk.cc

The `bitmap::find_free()` function locks and unlocks the bitmap blocks when checking a bitmap entry. It harms the performance when working on fragmented metadata (e.g., modify an existed metadata).

[space map disk] reduce the lock counts to speed up free block searching

---

base/file_utils.cc

Fixing coverity reported issue. No big deal...
Pull, please.

[*_restore] Fix leaking file descriptor

---

Makefile.in

[build] Fix static build by including contrib/Makefile early

---

thin-provisioning/thin_scan.cc

1. code refactoring: using generator pattern
2. performance improvement: for each block, calculate crc32c only once

[thin_scan] refactoring and performance improvement

---

base/application.cc
caching/cache_writeback.cc
thin-provisioning/metadata_dumper.cc
thin-provisioning/thin_dump.cc
thin-provisioning/thin_ls.cc

Fix compilation with uClibc

---

thin-provisioning/thin_metadata_pack.cc

Apply the approach used in thin_scan to speed-up metadata scanning. The improvement is not obvious compared to thin_scan, due to the long-running compression process.

[thin_metadata_pack] Improve block scanning performance

---

persistent-data/space-maps/recursive.cc
thin-provisioning/thin_generate_metadata.cc

- Revise thin_generate_metadata into a transactional tool
- Fix bugs in sm_recursive. Please refer to issue #70 for related info.

[thin_generate_metadata] Introduce the new transactional metadata generate tool

---

Makefile.in
base/io.h
base/io_generator.cc
base/io_generator.h
base/math_utils.h
base/types.h
block-cache/block_cache.h
block-cache/io_engine.h
caching/cache_metadata.h
persistent-data/data-structures/array.h
persistent-data/data-structures/bitset.cc
persistent-data/data-structures/btree-remove.tcc
persistent-data/data-structures/btree.h
persistent-data/data-structures/btree.tcc
persistent-data/file_utils.cc
persistent-data/space-maps/core.cc
persistent-data/space-maps/disk.cc
thin-provisioning/commands.cc
thin-provisioning/commands.h
thin-provisioning/device_tree.cc
thin-provisioning/device_tree.h
thin-provisioning/metadata.cc
thin-provisioning/metadata.h
thin-provisioning/thin_generate_mappings.cc
thin-provisioning/thin_generate_metadata.cc
thin-provisioning/thin_pool.cc
thin-provisioning/thin_pool.h

- Implement all the pool-messages in userland
- Make use of the thin_pool.cc
- Complete the btree deletion and removal features
- Introduce an fio-like mapping generation tool

Complete the major features of thin_generate_metadata, and introduce thin_generate_mappings

---

Cargo.lock
Cargo.toml
Makefile.in
thin-provisioning/commands.cc
thin-provisioning/commands.h
thin-provisioning/thin_delta.cc
thin-provisioning/thin_patch_superblock.cc

- Introduce thin_patch_superblock
- Cleanup thin_delta, and add debugging feature 
- Update Rust package version

thin development tools update

---

Makefile.in
base/command_interpreter.cc
base/command_interpreter.h
base/output_formatter.cc
base/output_formatter.h
caching/cache_debug.cc
caching/commands.h
caching/devel_commands.cc
thin-provisioning/commands.h
thin-provisioning/devel_commands.cc
thin-provisioning/thin_debug.cc

Features
- Enhanced error handling
- Compacted display formatting
- The superblock command now shows space map roots
- Added more debugging commands

[dbg] Integrate thin_debug, and add cache_debug

---

src/pdata/btree_leaf_walker.rs
src/thin/dump.rs
src/thin/runs.rs

This is not the final version. Just some quick fixes to make it runnable, for testing purpose.

Make thin_dump runnable

---

Makefile.in
base/application.cc
base/application.h
base/file_utils.cc
block-cache/io_engine.cc
caching/hint_array.cc
contrib/Makefile.in
era/restore_emitter.cc
thin-provisioning/cache_stream.cc
thin-provisioning/metadata_dumper.cc
thin-provisioning/shared_library_emitter.cc
thin-provisioning/thin_delta.cc
thin-provisioning/thin_dump.cc
thin-provisioning/thin_metadata_size.cc
thin-provisioning/thin_show_duplicates.cc
thin-provisioning/thin_show_metadata.cc
unit-tests/Makefile.in

Based on the scan result of v0.9.0 (d6d93c3)

Fix issues detected by Coverity

---

src/bin/thin_explore.rs
src/cache/writeback.rs
src/commands/cache_writeback.rs
src/commands/thin_check.rs
src/copier.rs
src/io_engine.rs
tests/thin_check.rs

- Fixed bugs in cache_writeback
- Replace seek by pread/pwrite
- Fix error in opening devices exclusively

Minor fixes

---

src/commands/cache_check.rs
src/commands/cache_dump.rs
src/commands/cache_generate_metadata.rs
src/commands/cache_metadata_size.rs
src/commands/cache_repair.rs
src/commands/cache_restore.rs
src/commands/cache_writeback.rs
src/commands/era_check.rs
src/commands/era_dump.rs
src/commands/era_invalidate.rs
src/commands/era_repair.rs
src/commands/era_restore.rs
src/commands/thin_check.rs
src/commands/thin_delta.rs
src/commands/thin_dump.rs
src/commands/thin_explore.rs
src/commands/thin_ls.rs
src/commands/thin_metadata_pack.rs
src/commands/thin_metadata_size.rs
src/commands/thin_metadata_unpack.rs
src/commands/thin_repair.rs
src/commands/thin_restore.rs
src/commands/thin_rmap.rs
src/commands/thin_shrink.rs
src/commands/thin_trim.rs
src/commands/utils.rs
src/pdata/btree_builder/test_utils.rs
src/pdata/btree_walker/tests.rs

- Fix an error introduced by the previous code merge
- Remove duplicate code

Fix devtools build errors

---

src/cache/dump.rs
src/cache/metadata_generator.rs
src/cache/xml.rs
src/commands/cache_dump.rs
src/commands/cache_generate_metadata.rs
src/commands/era_dump.rs
src/commands/thin_dump.rs
src/dump_utils.rs
src/era/dump.rs
src/era/xml.rs
src/lib.rs
src/pdata/array_walker.rs
src/thin/delta.rs
src/thin/dump.rs
src/thin/metadata.rs

- Terminate the process immediately on error
- Display repairing hints
- thin_dump --skip-mappings

Improve usability of thin/cache/era_dump

---

src/cache/metadata_generator.rs
src/cache/writeback.rs
src/io_engine/buffer.rs
src/io_engine/mod.rs
src/io_engine/sync_copier.rs
src/pdata/bitset.rs
tests/cache_writeback.rs
tests/common/cache.rs

- Fix malfunctioned metadata update
- Fix div-by-zero error while there's no blocks to copy
- Fix Cargo lints

cache_writeback fixes

---

doc/TODO.md
src/commands/thin_check.rs
src/io_engine/base.rs
src/io_engine/sync.rs
src/lib.rs
src/pdata/space_map/base.rs
src/thin/check.rs
src/utils/hashvec.rs
src/utils/mod.rs

- IO scheduling based on commit 1fb04b88 (branch 2022-07-25-thin-check-io-sched)
- Error-tolerant two-pass checking
- Improved error reporting
- Bug fixes

New thin_check with IO scheduling and more secure checking

---

src/pdata/btree.rs
src/pdata/btree_error.rs
src/pdata/btree_leaf_walker.rs
src/pdata/btree_merge.rs
src/pdata/btree_walker.rs
src/report.rs
src/thin/check.rs

- Reduce the memory consumption of cached node errors
- Remove unneeded trait implementation

thin_check minor fixes

---

src/commands/engine.rs
src/commands/utils.rs
src/thin/check.rs
src/thin/ls.rs
tests/common/target.rs
tests/thin_check.rs
tests/thin_dump.rs
tests/thin_ls.rs

- Fix opening live metadata in era_invalidate
- Fix reading metadata snapshot in thin_ls
- Tweak message outputs

Various fixes

---

src/commands/thin_explore.rs
src/commands/thin_generate_damage.rs
src/thin/damage_generator.rs
tests/thin_check.rs
tests/thin_dump.rs
tests/thin_repair.rs

Provide automated tests for some resolved bugs

More functional tests

---

src/commands/thin_delta.rs
src/pack/vm.rs
src/thin/delta.rs
src/thin/delta/tests.rs
src/thin/delta_visitor.rs
tests/common/thin.rs
tests/thin_delta.rs

Fix bugs in command line parsing and range construction

thin_delta bug fixes

---

Cargo.toml
examples/custom-emitter.rs
src/cache/dump.rs
src/dump_utils.rs
src/era/dump.rs
src/thin/dump.rs
tests/common/process.rs
tests/thin_dump.rs

- Fix cache_dump and era_dump outputs on broken pipe
- Tweak the broken_fifo test
- Code refactoring

cache_dump and era_dump fixes and refactoring

---

tests/common/thin_xml_generator.rs

Those generators are used in thin_merge tests as well.

Fix thin xml generators for tests

---

man8/thin_dump.txt
man8/thin_migrate.txt
src/thin/migrate/base.rs
src/thin/migrate/devices.rs

- Enforce read-only input devices
- Tweak the man pages

thin_migrate fixes
