jthornber/thin-provisioning-tools

thin-provisioning/thin_ls.cc
We are trying to get cadvisor filesystem stats support for devicemapper.  cadvisor expects to be able to get the device size in bytes.  This PR added new fields to get shared/exclusive/shared stats in bytes.
It seems we could also get this information from doing *_SECTORS and multiply by 512 (sector size, because block_size is the size of the block in sectors, not bytes).  But that isn't nearly as clean and understandable.
=> get stats in bytes

Makefile.in
```dlopen``` etc. require ```-ldl``` to link
fixes #54
=> use -ldl when linking

Makefile.in, persistent-data/data-structures/btree_counter.h, persistent-data/data-structures/btree_damage_visitor.h, persistent-data/data-structures/btree_node_checker.cc, persistent-data/data-structures/btree_node_checker.h, thin-provisioning/metadata_counter.cc, thin-provisioning/thin_check.cc, thin-provisioning/thin_ll_dump.cc
As mentioned in the comment of b2249599, I don't want counting_visitor to inherit btree_damage_visitor
https://github.com/jthornber/thin-provisioning-tools/commit/b22495997a8bf427741225ef86edf267ee746d7c
So I extracted the node checking functions into a stand-alone class btree_node_checker, and use it in btree_damage_visitor, counting_visitor, and thin_ll_dump.
Notes:
1. I don't want node_ref become a heavy-weight class, so the node checking functions are not members of node_ref. (unlike node_ref::value_sizes_match())
2. Error strings are returned by private members of btree_node_checker, because they only have meaning when error happened. (unlike that node_ref::value_mismatch_string() is public)
3. In the last two commits, I moved the new_root() call to the beginning of check_internal() …
=> Fix unnecessary value visiting in counting_visitor

Makefile.in, configure.ac, contrib/Makefile.in, contrib/tmakatos_emitter.cc, contrib/tmakatos_emitter.h, persistent-data/file_utils.cc, thin-provisioning/static_library_emitter.cc
With commit c7813e07e4d2b2d64120096bd8e9421d0dcf6083 3rd party emitters can be used only as shared objects. This pull request allows a 3rd party emitter to be statically compiled into the ```pdata_tools``` binary.
=> Allow 3rd party emitters to be statically compiled

Makefile.in, unit-tests/Makefile.in
- PHONY is misspelled
- fix the pdata_tools target dep
- add a "check" alias to match standard automake behavior
- mark test & check targets as phony
=> fix up test targets

Makefile.in
This patch fixes a compilation error when statically compiling thin provisioning tools.
=> don't use implicit rule when statically compiling emitters

base/output_file_requirements.cc, persistent-data/data-structures/btree.h, persistent-data/data-structures/btree.tcc, thin-provisioning/restore_emitter.cc, thin-provisioning/thin_ll_restore.cc, thin-provisioning/thin_pool.cc, thin-provisioning/thin_pool.h
1. thin_ll_restore allows the input subtrees to have duplicated keys, and the mapped values will be replaced by the later ones (see btree::insert() ). To avoid recounting the duplicated keys in restore emitter, I changed the return value of btree::insert() to bool to know whether the key was inserted or not.
2. Cherry-pick 44351860 from master, then adopt check_output_file_requirements() in thin_ll_restore.
=> Minor fixes for new dev-tools

caching/cache_writeback.cc, contrib/Makefile.in, thin-provisioning/static_library_emitter.cc
Building thin-provisioning tools on Ubuntu 16.04 (make 4.1, gcc 5.4.0) fails, this patch addresses the build failures.
=> fix compilation for gcc 5.4.0

block-cache/block_cache.cc
io_event::res is a signed int64 in kernel, but libaio defines it
as unsigned long. We should cast it to a signed value.
(Finally I cast it to <long> for safety)
=> [block-cache] Fix error handling in reading libaio events

Makefile.in, base/file_utils.cc, base/file_utils.h, base/xml_utils.cc, base/xml_utils.h, caching/cache_restore.cc, era/superblock.cc, persistent-data/block.tcc, persistent-data/block_counter.h, persistent-data/data-structures/bloom_filter.cc, persistent-data/data-structures/bloom_filter.h, persistent-data/data-structures/btree.tcc, persistent-data/file_utils.cc, persistent-data/file_utils.h, persistent-data/space-maps/careful_alloc.cc, persistent-data/space-maps/recursive.cc, persistent-data/validators.cc, thin-provisioning/cache_stream.cc, thin-provisioning/superblock.cc, thin-provisioning/thin_trim.cc
At first, I want to delegate `file_exist()`'s task to `persistent_data::check_file_exists`, but the dependency between those two headers does not allow me to do that. Therefore, I choose to factor out the file-related operations to `base/file-utils.{h,cc}`. The benefits are:
1. Eliminate the potential circular dependency between
`persistent-data/block.h` and `persistent-data/file_utils.h`,
if the former one wants to include the latter.
2. Avoid namespace pollution by removing the "using namespace std"
declaration in `block.tcc`.
3. Correct the header hierarchy: `base/xml_utils.h` now no longer
depends on the higher-level `persistent-data/file_utils.h`
4. Reduce the code size and compile time
=> Spin-off syscall-related file operations

Makefile.in
...and thin_show_duplicates symlinks.
The support for these is built only if --enable-dev-tools is used in
configure, thus we should install the symlinks conditionally.
Hi Joe, make install is creating a non working symlinks at the moment. Shall we remove those altogether?
I have not tested the moved thin_trim.cc yet.
-- Martian
=> Makefile: Conditional install of thin_trim

era/restore_emitter.cc
Note that clang++ has a lot more warnings; this is just to fix the build.  Tested on Gentoo Linux with clang-4.0.1 -stdlib=libc++ and gcc 7.2.0 (with libstdc++).
=> Fix build with libc++ by disambiguating std::bitset away.

caching/cache_check.cc, caching/superblock.cc, era/era_check.cc, era/superblock.cc, functional-tests/cache-functional-tests.scm, functional-tests/era-functional-tests.scm, persistent-data/file_utils.cc, persistent-data/file_utils.h, thin-provisioning/thin_check.cc
* not tested: some people complained about upstream ruby and new C++, but chez scheme? Rather an exotic implementation...
* not sure *persistent-data/file_utils.cc* is the best location for `check_for_xml`
* changed `bm->read_lock` to read from offset 0 when detecting file type instead of `superblock_detail::SUPERBLOCK_LOCATION` (which happens to be 0 too)
=> Detect XML in *_check tools

Makefile.in
The rule for lib/libft.so is only enabled with --enable-testing,
so the default target shouldn't depend unconditionally on it.
With the default configure options, the build failed with:
make: *** No rule to make target 'lib/libft.so', needed by 'all'.  Stop.
=> [functional-tests] fix build with testing disabled

README.md
The configure script doesn't exist until autoconf is run.
Signed-off-by: Todd Gill <tgill@redhat.com>
=> Add autoconf step to Building instructions

persistent-data/space-maps/careful_alloc.cc
Preserve the input block first to avoid reusing it in subsequent
shadow operations, e.g., shadow another block when releasing
a recursive lock. (issue #97)
=> [space map] fix accounting of allocatable blocks

thin-provisioning/emitter.h
This fixes following build failure with Boost 1.67.0:
```
In file included from /usr/include/boost/optional/optional.hpp:33,
from /usr/include/boost/optional.hpp:15,
from ./thin-provisioning/emitter.h:23,
from contrib/thin_sexp_emitter.cc:2:
/usr/include/boost/optional/optional.hpp: In instantiation of ‘std::basic_ostream<_CharT, _Traits>& boost::operator<<(std::basic_ostream<_CharT, _Traits>&, const boost::optional_detail::optional_tag&) [with CharType = char; CharTrait = std::char_traits<char>]’:
./base/indented_stream.h:31:9:   required from ‘{anonymous}::indented_stream& {anonymous}::indented_stream::operator<<(const T&) [with T = boost::optional<unsigned int>]’
contrib/thin_sexp_emitter.cc:105:29:   required from ‘void {anonymous}::sexp_emitter::kv(const char*, const T&) [with T = …
```
=> [build] Include boost/optional/optional_io.hpp in  thin-provisioning/emitter.h

block-cache/io_engine.h
There is a failure while compiling with libc musl:
[snip]
|./block-cache/io_engine.h:18:17: error: expected
unqualified-id before numeric constant
|  unsigned const PAGE_SIZE = 4096;
[snip]
The musl defeines macro PAGE_SIZE, undef it conditionally
could fix the issue.
http://musl.openwall.narkive.com/tO8vrHdP/why-musl-define-page-size
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
=> fix compile failed with libc musl

persistent-data/space-maps/disk.cc
Similar to issue #93, the bit_end will be wrong if the range end is a multiple of ENTRIES_PER_BLOCK.
=> [space-map-disk] fix the search range

Makefile.in, configure.ac, persistent-data/data-structures/btree_damage_visitor.cc, persistent-data/data-structures/btree_damage_visitor.h, thin-provisioning/metadata_checker.cc, thin-provisioning/metadata_checker.h, thin-provisioning/thin_check.cc
Concept
* A `metadata_checker` accept three parameters: the device file, the check_options for selective checking, and the output option.
Thoughts
* Is it good to invoke `print_info()` inside the metadata_checker?
* If we want to make metadata_checker more concise, we could move `check_for_xml()` and `print_info()` to thin_check.cc. On the other hand, if we want to make the components self-contained, then file-size-checking should be done in `open_bm()`
* `struct check_options` looks unstraightforward, and its reusability is uncertain (might not work for further checker variants). A better policy-based approach might be required to do selective checking.
=> Factor out metadata_checker and btree_damage_visitor.cc

persistent-data/block.h, persistent-data/block.tcc, persistent-data/space-maps/disk.cc
The `bitmap::find_free()` commit drastically improves the performance of finding free blocks in a fragmented space map. The improvement could be 10x or more while inserting millions of keys. thin_restore and thin_repair do not benefit from this change, since that the space map is not fragmented at the first transaction (i.e., all the blocks are shadowed).
There is still room for improvement. For example:
* Keep track of the "real" free blocks for the new transaction.
* In `sm_disk::find_free()`, avoid breaking a bitmap block into multiple spans, to reduce the number of read_locks, and also avoid accessing the same portion (in terms of 64-bit dereferencing) of a bitmap multiple times.
The first one might have more of an effect. However, I haven't had an idea yet.
=> Improve performance, and remove unused code

Makefile.in, base/io_generator.cc, base/io_generator.h, thin-provisioning/commands.cc, thin-provisioning/commands.h, thin-provisioning/damage_generator.cc, thin-provisioning/damage_generator.h, thin-provisioning/thin_generate_damage.cc, thin-provisioning/thin_generate_mappings.cc, thin-provisioning/thin_generate_metadata.cc, thin-provisioning/thin_pool.cc, thin-provisioning/thin_pool.h
Changes:
* Introduce thin_generate_damage to create leaked metadata blocks
* Enhance thin_generate_mappings: Add random map and mixed sequential-random mode
* Support setting the needs_check flag by using thin_generate_metadata
Further unit tests, functional tests, and code refinement will be made soon.
=> Enhance thin_generate_mappings, and introduce thin_generate_damage

Makefile.in, configure.ac, contrib/Makefile.in, unit-tests/Makefile.in
This is used on specific buildchains (nixos static builds for example).
=> autoconf: allow a user to override ar

Makefile.in, configure.ac, unit-tests/Makefile.in
The previous patch depends on the shell/environment variable `AR`, thus the string `AR` in Makefile won't be substituted if the corresponding shell/environment variable is not set.
=> [build] Fix the default value for the AR variable (#145)

functional-tests/command-line/thin-check.scm, functional-tests/scenario-string-constants.scm, functional-tests/thin-functional-tests.scm, thin-provisioning/mapping_tree.cc, thin-provisioning/mapping_tree.h, thin-provisioning/metadata.cc, thin-provisioning/metadata_checker.cc, thin-provisioning/metadata_checker.h, thin-provisioning/thin_check.cc, thin-provisioning/thin_generate_damage.cc
Changes:
- Add option --fix-metadata-leaks
- Change the policy of --clear-needs-check-flag to prevent error recurrence
- Functional tests (partially)
=> [thin_check] Support fixing leaked metadata blocks

base/io_generator.cc, base/sequence_generator.cc, persistent-data/block_counter.h, persistent-data/data-structures/btree_counter.h, persistent-data/space-maps/core.cc, persistent-data/space-maps/disk.cc, persistent-data/transaction_manager.h, thin-provisioning/damage_generator.cc, thin-provisioning/metadata_checker.cc, thin-provisioning/metadata_checker.h, thin-provisioning/metadata_counter.cc, thin-provisioning/metadata_counter.h, unit-tests/space_map_t.cc
- Address the silent error issue in space map blocks counting. Now a broken tree node or bitmap in space maps is treat as fatal error.
- Disable checking of data block ref-counts due to space and time complexity concerns. The structural checking is left to count_metadata().
- Add test cases for block allocation among multiple transactions
- Fix some bugs
=> thin_check enhancements

persistent-data/data-structures/btree_counter.h, tests/thin_check.rs, thin-provisioning/damage_generator.cc, thin-provisioning/metadata_checker.cc, thin-provisioning/metadata_checker.h, thin-provisioning/metadata_counter.cc, thin-provisioning/metadata_counter.h, unit-tests/btree_counter_t.cc, unit-tests/space_map_t.cc
This is a copy of PR #151
- thin_check
- Allow using `--clear-needs-check` and `--skip-mappings` together for backward compatibility (in reply to commit b278f4f)
- Count under populated nodes if `--ignore-non-fatal-errors` is provided
- thin_generate_damage
- Do not open transaction to prevent ref-count underflow
- Add unit tests
=> thin_check fixes

Makefile.in, base/application.cc, bin/thin_generate_damage, bin/thin_generate_mappings, bin/thin_generate_metadata, bin/thin_journal_check, bin/thin_ll_dump, bin/thin_ll_restore, bin/thin_scan, bin/thin_show_duplicates, bin/thin_show_metadata, caching/devel_commands.cc, configure.ac, era/devel_commands.cc, src/bin/thin_shrink.rs, tests/thin_delta.rs, thin-provisioning/commands.cc, thin-provisioning/commands.h, thin-provisioning/devel_commands.cc
- Build the dev-tools if the `--enable-testing` option is specified
- That is, the dev-tools won't be built if we're not intent to run the tests, to save the build time. (assumed that the Rust tests will become part of the `functional-test` target)
- Fix thin_delta help tests
- Merge the previous commit
=> [build] Enable building the dev-tools for functional tests

src/cache/check.rs, src/cache/dump.rs, src/cache/superblock.rs, src/cache/xml.rs, src/pdata/array_walker.rs, src/pdata/bitset.rs
- Fix array indexing
- Fix panic on empty array
- Remove trailing null characters from the policy name
- Change XML tag naming for backward compatibility
=> Fix bugs in array iteration and text outputs

thin-provisioning/restore_emitter.cc
It is not necessary to reserve the superblock flags especially the needs_check one, although the propagated flags could be cleared by thin_check during LVM pool activation.
=> Clear thin superblock flags in restored metadata

Cargo.toml, src/bin/cache_dump.rs, src/bin/thin_check.rs, src/bin/thin_dump.rs, src/cache/dump.rs, src/cache/restore.rs, src/pdata/array_builder.rs, src/pdata/btree_builder.rs, src/pdata/space_map.rs, src/pdata/space_map_checker.rs, src/pdata/space_map_common.rs, src/pdata/space_map_disk.rs, src/pdata/space_map_metadata.rs, src/thin/dump.rs, src/thin/restore.rs, src/write_batcher.rs, tests/cache_check.rs, tests/common/mod.rs, tests/thin_check.rs, tests/thin_delta.rs, tests/thin_repair.rs, tests/thin_restore.rs, tests/thin_rmap.rs, thin-provisioning/thin_delta.cc
- Fix errors in restored metadata
* Fix reference counts of btree nodes
* Fix overflowed index_entry::none_free_before
* Fix index_entry::nr_free in metadata space map
* Allow packing unaligned number of bitmap entries (unaligned to 32 entries) for fast initialization
- Improve performance a little
* Build metadata space map in-place (No extra space map or block set is required)
* Do not copy & iterate btree leaves twice while building thin mapping trees
* Remove unnecessary data copying in array construction
- Enable testing the Rust targets
=> Fix restoration tools

Makefile.in
This was previously needed for `thin-provisioning/thin_metadata_pack.cc`
but that file was rewritten in Rust and no longer needs Boost. The flag
causes every binary to have a completely redundant depedency on
libboost_iostream.so, which is an [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1974781) for RHEL packaging.
The flag was added in 0e1700fbe9e34c58f1019a0c425fad9e62db24a3 and made redundant by 61de3f92873310d8a25a8392f7e53ef67cc3d88c.
I've only tested that everything still builds with this change.
=> [build] Remove -lboost_iostreams linker flag

base/file_utils.cc, functional-tests/cache-functional-tests.scm, functional-tests/era-functional-tests.scm, src/bin/thin_explore.rs, src/bin/thin_metadata_unpack.rs, src/bin/thin_shrink.rs, src/io_engine.rs, src/pack/node_encode.rs, src/pack/toplevel.rs, src/pdata/btree_leaf_walker.rs, tests/cache_check.rs, tests/cache_dump.rs, tests/common/common_args.rs, tests/common/input_arg.rs, tests/common/mod.rs, tests/common/output_option.rs, tests/thin_check.rs, tests/thin_delta.rs, tests/thin_dump.rs, tests/thin_metadata_pack.rs, tests/thin_metadata_unpack.rs, tests/thin_repair.rs, tests/thin_restore.rs, tests/thin_rmap.rs
- Pull out common tests on I/O options into reusable modules
- Add basic tests for cache_dump
- Minor fixes on I/O options
* thin_repair: Check the input file type before repairing, to ensure the output file is untouched
* thin_metadata_pack: Fix truncated output file on invalid input
* Refine error messages
=> Functional tests revised

src/bin/cache_repair.rs, src/bin/cache_restore.rs, src/bin/thin_repair.rs, src/bin/thin_restore.rs, src/cache/dump.rs, src/cache/ir.rs, src/cache/mod.rs, src/cache/repair.rs, src/cache/restore.rs, src/cache/xml.rs, src/shrink/toplevel.rs, src/thin/dump.rs, src/thin/ir.rs, src/thin/metadata.rs, src/thin/mod.rs, src/thin/repair.rs, src/thin/restore.rs, src/thin/xml.rs, tests/common/cache_xml_generator.rs, tests/common/input_arg.rs, tests/common/thin.rs, tests/common/thin_xml_generator.rs, tests/thin_shrink.rs
- Clean up the optimization process of thin_dump
* Use common leaf sequences to build shared-defs, thus remove previous code and comments about shared internals. (e.g., https://github.com/jthornber/thin-provisioning-tools/blob/main/src/thin/dump.rs#L251)
- Added thin_repair and cache_repair
=> First pass at thin_repair and cache_repair

era/metadata.cc
Until now, `era_invalidate` read the live metadata (superblock), instead of the metadata snapshot, when using the `--metadata-snapshot` parameter.
Fix this by passing the location of the metadata snapshot to `open_metadata()`, when a metadata snapshot is used.
=> [era_invalidate] Don't read the live metadata when the --metadata-snapshot option is provided

Cargo.toml
The version 2 resolver that comes with edition 2021 doesn't enable features in dev-dependencies unless necessary so that the dev-tools won't be compiled in non-testing builds.
References:
https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
https://doc.rust-lang.org/cargo/reference/features.html
=> Update Rust edition to 2021

src/bin/pdata_tools.rs, src/bin/pdata_tools_dev.rs, src/thin/metadata_repair.rs
These patches are specific to metadata with a great number of root candidates (e.g., bz2082197).
- Reduce the time complexity from O(n^2)  to O(n*log(n)) in average.
- Avoid repeated map lookup
=> Improve the process of find_roots() in thin_repair

src/cache/writeback.rs, src/commands/cache_writeback.rs, src/io_engine/base.rs, src/io_engine/copier.rs, src/io_engine/mod.rs, src/io_engine/ramdisk.rs, src/io_engine/rescue_copier.rs, src/io_engine/rescue_copier/tests.rs, src/io_engine/sync_copier.rs, src/io_engine/sync_copier/tests.rs, src/io_engine/test_utils.rs, src/io_engine/utils.rs, src/io_engine/utils/tests.rs, src/lib.rs, src/pdata/btree_walker.rs, src/random.rs, tests/cache_writeback.rs, tests/common/mod.rs, tests/thin_shrink.rs
- Decouple the Copier from physical files, by introducing the abstraction layers for block io and vectored read/write.
- Handle blocks ignored by vectored read/write with direct io
- Try harder to maximize data recovery rate by copying failure blocks page-by-page
- Add unit tests for the Copiers. The tests include error handling and data integrity.
- Minor enhancements: Improve efficiency of v1 metadata update; remove unnecessary locks
=> Improve error handling of cache_writeback

src/cache/check.rs, src/cache/writeback.rs, src/commands/cache_writeback.rs, src/commands/engine.rs, src/write_batcher.rs, tests/cache_writeback.rs
- Force users to repair the metadata before writeback cache
- Fix error returning in cache_check
=> Disallow using corrupted metadata in cache_writeback

doc/TODO.md, src/cache/writeback.rs, src/commands/cache_check.rs, src/commands/cache_repair.rs, src/commands/cache_restore.rs, src/commands/cache_writeback.rs, src/commands/era_check.rs, src/commands/era_dump.rs, src/commands/era_repair.rs, src/commands/era_restore.rs, src/commands/thin_check.rs, src/commands/thin_dump.rs, src/commands/thin_repair.rs, src/commands/thin_restore.rs, src/commands/thin_trim.rs, src/pdata/array.rs, src/pdata/array_walker.rs, src/pdata/bitset.rs, src/pdata/btree_error.rs, src/pdata/btree_walker.rs, src/report.rs, src/thin/check.rs
thin_check:
- Check key range mismatch between internal nodes
- Fix device selection for metadata snap checking
- Fix progress bar positioning
- Check blocknr in btree node header
Others:
- Simplify error representation for arrays
- Enable log levels
=> thin_check minor fixes

src/commands/era_invalidate.rs, src/commands/thin_delta.rs, src/commands/thin_ls.rs, src/era/invalidate.rs, src/thin/check.rs, src/thin/dump.rs
This PR fixes two issues:
- Some commands (`era_invalidate`, `thin_delta` and `thin_ls`) used the wrong arg name for the `--metadata-snap` option - it should be `METADATA_SNAPSHOT` in order to be picked up by `commands::engine::parse_engine_opts`
- Some command implementations (`era::invalidate`, `thin::check` and `thin::dump`) don't correctly call `exclusive()` based on whether a metadata snapshot is being used
For the setting of `exclusive()` I reverted to usage C++ codebase's `open_bm()` function. (I'm not familiar particularly with dm-era).
I hope this is the correct behaviour!
=> Fix metadata snapshot option in a few places

src/cache/metadata_size.rs
`(usize * usize) as u64` does not cast early enough; the multiplication can still overflow
closes #248
=> [cache_metadata_size] fix build on 32-bit

Cargo.lock, Cargo.toml, src/cache/writeback.rs, src/commands/cache_metadata_size.rs, src/copier/sync_copier.rs, src/era/dump.rs, src/io_engine/spindle.rs, src/io_engine/utils.rs, src/io_engine/utils/tests.rs, src/pack/toplevel.rs, src/pack/vm.rs, src/pdata/array_builder/test_utils.rs, src/pdata/array_walker.rs, src/pdata/bitset.rs, src/pdata/btree.rs, src/pdata/btree_error.rs, src/pdata/space_map/base.rs, src/pdata/space_map/common.rs, src/thin/check.rs, src/thin/ls.rs, src/thin/metadata.rs, src/thin/restore.rs, src/thin/trim.rs, tests/common/output_option.rs, tests/common/thin_xml_generator.rs, tests/thin_check.rs, tests/thin_shrink.rs
- crc32c: Apply the patches from pr#35 to fix the endianness issue
- Fix the output file permission test
=> Fix incorrect crc32c outputs on big endian targets

src/commands/thin_explore.rs, src/commands/thin_stat.rs, src/commands/utils.rs, src/thin/dump.rs, src/thin/metadata.rs, src/thin/runs.rs, src/thin/stat.rs
- Fix a regression in thin_dump causing that it cannot keep shared defs with only one predecessor
- Improve error message display
- Minor fixes and enhancements for development tools
=> Fix a thin_dump regression and other minor issues

src/file_utils.rs, src/thin/trim.rs
Before this PR, the build would fail with this error:
```
error[E0308]: mismatched types
--> src/file_utils.rs:59:28
|
59  |         if libc::ioctl(fd, BLKGETSIZE64 as libc::c_ulong, &mut cap) == 0 {
|            -----------     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `u32`
|            |
|            arguments to this function are incorrect
|
note: function defined here
--> /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.142/src/unix/linux_like/linux/musl/mod.rs:739:12
|
739 |     pub fn ioctl(fd: ::c_int, request: ::c_int, ...) -> ::c_int;
|            ^^^^^
help: you can convert a `u32` to an `i32` and panic if the converted value doesn't fit
|
59  |         if libc::ioctl(fd, (BLKGETSIZE64 as libc::c_ulong).try_into().unwrap(), &mut cap) == 0 {
| …
```
=> [build] fix build on musl

Makefile
Some distros, such as Void Linux, build binaries not to `target/release`, but to `target/${RUST_TARGET}/release`.
=> [build] allow overriding PDATA_TOOLS in Makefile

Cargo.toml
The SPDX is a standard way to encode license information used by cargo/crates.io, nps, python, fedora and others
=> [build] Update license to SPDX identifier

src/bin/pdata_tools_dev.rs, src/cache/check.rs, src/cache/damage_generator.rs, src/cache/mod.rs, src/commands/cache_generate_damage.rs, src/commands/mod.rs, src/devtools/damage_generator.rs, src/devtools/mod.rs, src/lib.rs, src/thin/damage_generator.rs, src/thin/delta.rs, tests/cache_check.rs, tests/cache_dump.rs, tests/common/cache.rs, tests/common/era.rs, tests/common/mod.rs, tests/common/piping.rs, tests/common/target.rs, tests/era_dump.rs, tests/thin_dump.rs
- Extend cache_check's --clear-needs-check-flag option to have auto-repair caps
- Add tests for cache_check --auto-repair and --clear-needs-check-flag
- Add broken pipe tests for cache_dump and era_dump
=> Improve cache_check auto-repair policies
